### ISSUE TITLE
Data download

### ISSUE THREAD

**Issue by Wihandebeer** [kvsnoufal/portfolio-optimization#2]
Hi I could not download any data from this link, thank you.

**Comment by lshihui** [comment]
Hi, I could not access to data via the link. Appreciate if you could help with this. Thanks.

**Comment by zhulibjtu** [comment]
Could you kindly give us the data ?

**Comment by kvsnoufal** [comment]
I have uploaded the files in the below links:
1. https://www.mediafire.com/file/g05yja1uiilhfuu/cleaned.csv/file
2.
https://www.mediafire.com/file/xivks3xf64b83ph/cleaned_preprocessed.csv/file
